<script setup lang="ts">
import { computed } from "vue";

defineEmits(["back"]);

const contactEmail = computed(() => "falarikae.dev" + "@" + "gmail.com");
</script>

<template>
  <div class="privacy-page">
    <div class="back-btn-wrapper">
      <button @click="$emit('back')" class="back-btn">← Back to About</button>
    </div>

    <h2>Privacy Policy</h2>
    <p class="last-updated">Last updated: 25.2.2026</p>
    <p>
      This tool is an independent community-created calculator for WalkScape. It
      is not operated by Not a Cult Oy.
    </p>

    <section class="policy-section">
      <h3>1. Data Collected</h3>
      <p>This tool stores the following information:</p>
      <ul>
        <li>
          A randomly generated UUID stored in your browser's local storage.
        </li>
        <li>Game-related data you voluntarily input (items, levels, stats).</li>
        <li>
          The timestamp of your last activity, used to measure active users and
          identify inactive accounts for eventual cleanup.
        </li>
        <li>Temporary server logs generated by the hosting environment.</li>
      </ul>
      <p>
        No usernames, email addresses, or identifying information are collected.
      </p>
    </section>

    <section class="policy-section">
      <h3>2. Purpose of Processing</h3>
      <p>The data is processed solely to:</p>
      <ul>
        <li>Provide calculator and optimisation functionality.</li>
        <li>
          Allow returning users to retrieve their previously entered data.
        </li>
      </ul>
    </section>

    <section class="policy-section">
      <h3>3. Legal Basis</h3>
      <p>
        Processing is necessary for the performance of a service requested by
        the user (Article 6(1)(b) GDPR).
      </p>
    </section>

    <section class="policy-section">
      <h3>4. Storage and Retention</h3>
      <ul>
        <li>Your UUID is stored in your browser local storage.</li>
        <li>Game data is stored on the server and linked only to your UUID.</li>
        <li>Data is retained as long as your UUID remains active.</li>
        <li>
          Accounts that have been inactive for an extended period may be
          automatically deleted.
        </li>
        <li>
          You may delete all your data at any time through the app's settings.
          This will permanently remove all stored data and generate a new UUID.
        </li>
      </ul>
    </section>

    <section class="policy-section">
      <h3>5. Hosting</h3>
      <p>
        This tool is hosted on a server provided by Hetzner and paid for by Not
        a Cult Oy, who kindly allow it to share their infrastructure. The hosting
        environment may generate standard technical logs (e.g., IP addresses)
        for security and operational purposes.
      </p>
    </section>

    <section class="policy-section">
      <h3>6. Data Sharing</h3>
      <p>No data is shared with third parties.</p>
    </section>

    <section class="policy-section">
      <h3>7. Your Rights</h3>
      <p>If you are located in the European Union, you have the right to:</p>
      <ul>
        <li>Request access to your data</li>
        <li>Request deletion of your data</li>
        <li>Request correction of inaccurate data</li>
      </ul>
      <p>
        You can delete all your stored data directly through the app's settings.
        For all other requests, contact:
        <a :href="'mailto:' + contactEmail">{{ contactEmail }}</a>
      </p>
    </section>
  </div>
</template>

<style scoped lang="scss">
.privacy-page {
  display: flex;
  flex-direction: column;
  gap: $lg;
  padding: $xlg;

  .last-updated {
    opacity: 0.6;
    font-size: 0.9em;
  }

  .policy-section {
    display: flex;
    flex-direction: column;
    gap: $sm;

    ul {
      list-style-type: none;
      padding-left: $md;

      li {
        text-align: center;
      }
    }
  }
}

.back-btn-wrapper {
  align-self: flex-start;
  margin-bottom: $xlg;

  .back-btn {
    cursor: pointer;

    &:hover {
      opacity: 1;
      text-decoration: underline;
    }
  }
}
</style>
